apiVersion: v1
kind: Service
metadata:
  name: renter-easy-node-port
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: renter-easy-api-app
  ports:
    - port: 3000
      nodePort: 30000
